version: '3.3'
services: 
  backend_users:
    build: ../taller2-ubademy-users
    container_name: backend_users
    image: backend_users
    expose:
      - "8001"
    volumes:
      - ./../taller2-ubademy-users:/app
      
  backend_business:
    build: ../taller2-ubademy-business
    container_name: backend_business
    image: backend_business
    expose:
      - "8002"
    volumes:
      - ./../taller2-ubademy-business:/app 
      - /app/node_modules

  backend_api_gateway:
    build: .
    container_name: backend_api_gateway
    image: backend_api_gateway
    ports:
      - "8516:8000"
    expose:
      - "8000"
    volumes:
      - ./:/app
    depends_on:
      - backend_users
      - backend_business

