version: '3.3'
services:

  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './../taller2-ubademy-users/compose_postgres_db/postgres_data:/var/lib/postgresql/data'
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_PASSWORD=123456
    expose:
      - "5432"

  backend_users:
    build: ../taller2-ubademy-users
    container_name: backend_users
    image: backend_users
    expose:
      - "8001"
    volumes:
      - ./../taller2-ubademy-users:/app
    depends_on:
      - postgres

  mongodb_business:
    container_name: mongodb_business
    image: mongo
    expose:
      - "27017"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./../taller2-ubademy-business/compose_mongodb/database:/data/db

  backend_business:
    build: ../taller2-ubademy-business
    container_name: backend_business
    image: backend_business
    expose:
      - "8002"
    volumes:
      - ./../taller2-ubademy-business:/app 
      - /app/node_modules
    depends_on:
      - mongodb_business
      
  backend_payments:
    build: ../taller2-ubademy-payments
    container_name: backend_payments
    image: backend_payments
    expose:
      - "8003"
    volumes:
      - ./../taller2-ubademy-payments:/app
      - /app/node_modules
    depends_on:
      - backend_business

  backend_payments:
    build: ../taller2-ubademy-payments
    container_name: backend_payments
    image: backend_payments
    expose:
      - "8003"
    volumes:
      - ./../taller2-ubademy-payments:/app
      - /app/node_modules
    depends_on:
      - backend_business

  backend_api_gateway:
    build: .
    container_name: backend_api_gateway
    image: backend_api_gateway
    ports:
      - "8516:8000"
    expose:
      - "8000"
    volumes:
      - ./:/app
    depends_on:
      - backend_users
      - backend_business
      - backend_payments

