version: '3.3'
services: 
  backend_users:
    build: ../taller2-ubademy-users
    container_name: backend_users
    image: backend_users
    expose:
      - "8001"
    volumes:
      - ./../taller2-ubademy-users:/app

  mongodb_business:
    container_name: mongodb_business
    image: mongo
    expose:
      - "27017"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./../taller2-ubademy-business/compose_mongodb/database:/data/db

  backend_business:
    build: ../taller2-ubademy-business
    container_name: backend_business
    image: backend_business
    expose:
      - "8002"
    volumes:
      - ./../taller2-ubademy-business:/app 
      - /app/node_modules
    depends_on:
      - mongodb_business

  backend_api_gateway:
    build: .
    container_name: backend_api_gateway
    image: backend_api_gateway
    ports:
      - "8516:8000"
    expose:
      - "8000"
    volumes:
      - ./:/app
    depends_on:
      - backend_users
      - backend_business

