name: test-workflow
on:
  push:
    branches:
      main
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: pip install pytest-cov
      - run: pip install codecov
      - run: pytest --cov=./ --cov-report=xml
      
      - name: Upload coverage to Codecov
        run: codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage.xml
